import React from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import * as XLSX from 'xlsx';
import {
  AlertTriangle, BarChart3, Bell, BriefcaseBusiness, CalendarDays, CheckCircle2,
  ClipboardCheck, Database, Download, Edit3, Eye, FileText, Filter, Folder,
  Gauge, Home, KanbanSquare, Languages, LayoutList, Link as LinkIcon, Mail,
  MoreHorizontal, Plus, RefreshCcw, Search, Settings, Share2, ShieldCheck,
  Sparkles, Upload, Users, Workflow
} from 'lucide-react';
import './styles.css';
import './sharepoint-sync.css';

const COPY = {
  ar: {
    app: 'Project Control Hub', subtitle: 'نظام إدارة مشاريع وفرق وتقارير احترافي', search: 'بحث في النظام', upload: 'رفع Excel', newItem: 'إضافة', export: 'تصدير', share: 'مشاركة', refresh: 'تحديث', live: 'مصدر البيانات', synced: 'متصل ببيانات SharePoint', sample: 'بيانات تجريبية',
    nav: { dashboard: 'الرئيسية', portfolio: 'المحفظة', board: 'لوحة التحكم', tasks: 'المهام', risks: 'المخاطر', teams: 'الفريق', reports: 'التقارير', files: 'الملفات', databases: 'القوائم', automation: 'الأتمتة', settings: 'الإعدادات' },
    hero: 'مركز التحكم التنفيذي', desc: 'إدارة المشاريع والمهام والمخاطر والموارد والملفات والتقارير من SharePoint والموقع في مساحة واحدة.', all: 'الكل', on: 'على المسار', delayed: 'متأخر', blocked: 'متعثر', done: 'مكتمل', project: 'المشروع', owner: 'المالك', status: 'الحالة', priority: 'الأولوية', progress: 'الإنجاز', due: 'الموعد', actions: 'إجراءات', weekly: 'التقرير الأسبوعي', monthly: 'التقرير الشهري', executive: 'التقرير التنفيذي'
  },
  en: {
    app: 'Project Control Hub', subtitle: 'Professional project, team and reporting management', search: 'Search workspace', upload: 'Upload Excel', newItem: 'New', export: 'Export', share: 'Share', refresh: 'Refresh', live: 'Data Source', synced: 'Connected to SharePoint data', sample: 'Sample data',
    nav: { dashboard: 'Home', portfolio: 'Portfolio', board: 'Control Board', tasks: 'Tasks', risks: 'Risks', teams: 'Team', reports: 'Reports', files: 'Files', databases: 'Databases', automation: 'Automation', settings: 'Settings' },
    hero: 'Executive Control Center', desc: 'Manage projects, tasks, risks, resources, files and reports from SharePoint and the web portal in one workspace.', all: 'All', on: 'On Track', delayed: 'Delayed', blocked: 'Blocked', done: 'Completed', project: 'Project', owner: 'Owner', status: 'Status', priority: 'Priority', progress: 'Progress', due: 'Due', actions: 'Actions', weekly: 'Weekly Report', monthly: 'Monthly Report', executive: 'Executive Report'
  }
};

const SAMPLE = {
  source: { type: 'sample', siteUrl: 'https://leaderig.sharepoint.com/sites/Solution', updatedAt: new Date().toISOString() },
  projects: [
    { id: 'P-001', ar: 'بوابة العملاء', en: 'Customer Portal', owner: 'Haitham Elmohamady', status: 'delayed', progress: 56, priority: 'High', due: '2026-06-15', budget: 72, util: 84, tasks: 18, risks: 3, files: 24 },
    { id: 'P-002', ar: 'نظام ERP', en: 'ERP System', owner: 'Sara Al-Mutairi', status: 'on', progress: 76, priority: 'Medium', due: '2026-07-30', budget: 64, util: 73, tasks: 12, risks: 1, files: 18 },
    { id: 'P-003', ar: 'تحديث البنية التحتية', en: 'Infrastructure Upgrade', owner: 'Mohammed Al-Harbi', status: 'blocked', progress: 31, priority: 'Critical', due: '2026-05-20', budget: 91, util: 96, tasks: 22, risks: 5, files: 37 },
    { id: 'P-004', ar: 'تطبيق الهاتف', en: 'Mobile App', owner: 'Manal Al-Sharif', status: 'on', progress: 82, priority: 'Medium', due: '2026-08-10', budget: 55, util: 68, tasks: 9, risks: 1, files: 15 },
    { id: 'P-005', ar: 'تحليل البيانات والذكاء الاصطناعي', en: 'AI Analytics', owner: 'Ali Al-Qahtani', status: 'done', progress: 100, priority: 'Low', due: '2026-04-30', budget: 49, util: 61, tasks: 4, risks: 0, files: 31 }
  ],
  tasks: [], risks: [], resources: [], reports: [], files: [], sheets: []
};

function norm(v){ return v == null ? '' : String(v).replace(/\s+/g,' ').trim(); }
function n(p, lang){ return lang === 'ar' ? (p.ar || p.title || p.name || p.en) : (p.en || p.title || p.name || p.ar); }
function st(s, lang){ const ar={on:'على المسار',delayed:'متأخر',blocked:'متعثر',done:'مكتمل',open:'مفتوح',closed:'مغلق'}; const en={on:'On Track',delayed:'Delayed',blocked:'Blocked',done:'Completed',open:'Open',closed:'Closed'}; return (lang==='ar'?ar:en)[s] || s || '—'; }
function pr(p, lang){ const ar={Critical:'حرج',High:'عالي',Medium:'متوسط',Low:'منخفض'}; return lang==='ar' ? (ar[p]||p||'—') : (p||'—'); }
function statusFromText(value, progress=0){ const t=norm(value).toLowerCase(); if(t.includes('complete')||t.includes('مكتمل')||t.includes('تم')) return 'done'; if(t.includes('block')||t.includes('تعثر')||t.includes('critical')) return 'blocked'; if(t.includes('delay')||t.includes('متأخر')||t.includes('risk')) return 'delayed'; if(progress>=95) return 'done'; if(progress>=70) return 'on'; if(progress>=45) return 'delayed'; return 'blocked'; }
function sheetToRows(ws){ const m=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''}); const hi=Math.max(0,m.findIndex(r=>r.filter(c=>norm(c)).length>=3)); const headers=(m[hi]||[]).map((h,i)=>norm(h)||`Column ${i+1}`); const rows=m.slice(hi+1).map(r=>headers.map((_,i)=>norm(r[i]))).filter(r=>r.some(Boolean)); return {headers,rows}; }
function parseWorkbook(workbook,fileName){ const sheets=workbook.SheetNames.map(name=>({name,...sheetToRows(workbook.Sheets[name])})); const rows=(sheets.find(s=>s.name==='PMO Projects' || s.name==='Projects' || s.name==='ERP Project')?.rows||sheets.flatMap(s=>s.rows.slice(0,2))); const projects=rows.slice(0,60).map((r,i)=>{ const progress=Number(r.find(x=>String(x).includes('%'))?.replace('%','')) || Math.min(100,Math.max(18,34+((i*13)%66))); const status=statusFromText(r.join(' '), progress); return { id:r[0]||`P-${String(i+1).padStart(3,'0')}`, ar:r[1]||r[0]||`مشروع ${i+1}`, en:r[1]||r[0]||`Project ${i+1}`, owner:r[2]||r[7]||r[6]||'Project Manager', status, progress, priority:status==='blocked'?'Critical':status==='delayed'?'High':status==='on'?'Medium':'Low', due:r[5]||r[10]||r[9]||'2026-12-30', budget:45+((i*9)%55), util:50+((i*7)%45), tasks:5+((i*3)%24), risks:status==='blocked'?5:status==='delayed'?2:status==='on'?1:0, files:10+((i*4)%36)}; }); return { ...SAMPLE, source:{type:'excel', workbook:fileName, updatedAt:new Date().toISOString()}, sheets, projects:projects.length?projects:SAMPLE.projects }; }
function normalizeSharePointData(json){ const projects=(json.projects||json.PMOProjects||[]).map((p,i)=>{ const progress=Number(p.progress ?? p.Progress ?? p.PMOProgress ?? 0) || Math.min(100,30+((i*13)%70)); const status=statusFromText(p.status ?? p.Status ?? p.PMOStatus ?? p.health, progress); return { id:p.id||p.ID||p.ProjectID||`P-${String(i+1).padStart(3,'0')}`, ar:p.ar||p.ProjectName||p.Title||p.name||`مشروع ${i+1}`, en:p.en||p.ProjectName||p.Title||p.name||`Project ${i+1}`, owner:p.owner||p.ProjectManager||p.PMOProjectManager||'Project Manager', status, progress, priority:p.priority||p.Priority||(status==='blocked'?'Critical':status==='delayed'?'High':status==='on'?'Medium':'Low'), due:p.due||p.DueDate||p.PMODueDate||'', budget:Number(p.budget||p.Budget||0)||60, util:Number(p.util||p.Utilization||p.PMOUtilization||0)||70, tasks:Number(p.tasks||p.Tasks||0)||0, risks:Number(p.risks||p.Risks||0)||0, files:Number(p.files||p.Files||0)||0, link:p.link||p.FilesLink||p.PMOFilesLink}; }); return { ...SAMPLE, ...json, projects:projects.length?projects:SAMPLE.projects, source: json.source || {type:'sharepoint-json', updatedAt:new Date().toISOString()} }; }
function Chip({type,children}){ return <span className={`chip ${type}`}>{children}</span>; }
function Progress({value,tone='blue'}){ return <div className="progress"><span><i className={tone} style={{width:`${Math.max(0,Math.min(100,value||0))}%`}} /></span><b>{value||0}%</b></div>; }
function Cmd({icon:Icon,label,tone='',onClick}){ return <button className={`commandButton ${tone}`} onClick={onClick}><Icon size={16}/><span>{label}</span></button>; }
function Stat({icon:Icon,title,value,sub,tone}){ return <motion.div className="statCard" whileHover={{y:-4}}><div className={`statIcon ${tone}`}><Icon size={22}/></div><div><p>{title}</p><strong>{value}</strong><span>{sub}</span></div></motion.div>; }

function TopBar({t,lang,setLang,upload,source}){ return <header className="topBar"><div className="brand"><div className="brandLogo"><Workflow size={23}/></div><div><b>{t.app}</b><span>{t.subtitle}</span></div></div><div className="globalSearch"><Search size={18}/><input placeholder={t.search}/></div><div className="dataSource"><Database size={15}/><span>{source?.type === 'sharepoint' ? t.synced : t.sample}</span></div><div className="topActions"><label className="uploadBtn"><Upload size={16}/>{t.upload}<input type="file" accept=".xlsx,.xls,.xlsm" onChange={upload}/></label><button onClick={()=>setLang(lang==='ar'?'en':'ar')}><Languages size={17}/>{lang==='ar'?'EN':'AR'}</button><button><Bell size={17}/></button><button><Settings size={17}/></button></div></header>; }
function Sidebar({t,page,setPage}){ const nav=[['dashboard',Home],['portfolio',BriefcaseBusiness],['board',KanbanSquare],['tasks',ClipboardCheck],['risks',AlertTriangle],['teams',Users],['reports',BarChart3],['files',Folder],['databases',Database],['automation',Workflow],['settings',Settings]]; return <aside className="sidebar"><div className="workspaceCard"><Sparkles size={18}/><div><b>PMO Workspace</b><span>SharePoint + Portal</span></div></div><nav>{nav.map(([k,Icon])=><button key={k} className={page===k?'active':''} onClick={()=>setPage(k)}><Icon size={18}/><span>{t.nav[k]}</span></button>)}</nav><div className="sideNote"><ShieldCheck size={18}/><p>SharePoint lists, Excel, files and reports are unified in this portal.</p></div></aside>; }
function PageHero({t,page,source}){ return <section className="pageHero"><div><div className="breadcrumb"><Home size={14}/><span>PMO</span><span>/</span><span>{page}</span></div><h1>{t.hero}</h1><p>{t.desc}</p><div className="syncInfo"><RefreshCcw size={14}/><span>{source?.siteUrl || source?.workbook || 'Local portal'} • {source?.updatedAt ? new Date(source.updatedAt).toLocaleString() : ''}</span></div></div><div className="heroActions"><Cmd icon={Plus} label={t.newItem} tone="primary"/><Cmd icon={RefreshCcw} label={t.refresh}/><Cmd icon={Download} label={t.export}/><Cmd icon={Share2} label={t.share}/></div></section>; }
function FilterDock({t,filters,setFilters,owners}){ return <section className="filterDock"><div><Filter size={16}/><b>{t.status}</b></div><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="all">{t.all}</option><option value="on">{t.on}</option><option value="delayed">{t.delayed}</option><option value="blocked">{t.blocked}</option><option value="done">{t.done}</option></select><select value={filters.owner} onChange={e=>setFilters({...filters,owner:e.target.value})}>{owners.map(o=><option value={o} key={o}>{o==='all'?t.all:o}</option>)}</select><select value={filters.progress} onChange={e=>setFilters({...filters,progress:e.target.value})}><option value="all">{t.progress}: {t.all}</option><option value="low">&lt; 50%</option><option value="mid">50% - 80%</option><option value="high">&gt; 80%</option></select></section>; }
function PortfolioHealth({t,projects}){ const total=projects.length||1; const c={on:projects.filter(p=>p.status==='on').length,delayed:projects.filter(p=>p.status==='delayed').length,blocked:projects.filter(p=>p.status==='blocked').length,done:projects.filter(p=>p.status==='done').length}; return <div className="panelPro"><div className="panelHeader"><h3>{t.nav.portfolio}</h3><MoreHorizontal size={18}/></div><div className="pulseBody"><div className="donutPro" style={{background:`conic-gradient(#16a34a 0 ${(c.on/total)*100}%, #d97706 ${(c.on/total)*100}% ${((c.on+c.delayed)/total)*100}%, #dc2626 ${((c.on+c.delayed)/total)*100}% ${((c.on+c.delayed+c.blocked)/total)*100}%, #94a3b8 ${((c.on+c.delayed+c.blocked)/total)*100}% 100%)`}}><span>{projects.length}</span></div><div className="legendPro"><p><i className="green"/>{t.on}<b>{c.on}</b></p><p><i className="amber"/>{t.delayed}<b>{c.delayed}</b></p><p><i className="red"/>{t.blocked}<b>{c.blocked}</b></p><p><i className="gray"/>{t.done}<b>{c.done}</b></p></div></div></div>; }
function Alerts({t,lang,projects}){ const alerts=projects.filter(p=>['blocked','delayed'].includes(p.status)).slice(0,4); return <div className="panelPro"><div className="panelHeader"><h3>{t.nav.automation}</h3><Bell size={18}/></div><div className="alertList">{alerts.map(p=><div className="alertItem" key={p.id}><span className={`alertDot ${p.status}`}/><div><b>{n(p,lang)}</b><p>{lang==='ar'?'تحتاج متابعة وخطة عمل':'Needs follow-up and action plan'}</p></div><Chip type={p.status}>{st(p.status,lang)}</Chip></div>)}</div></div>; }
function WorkflowPanel({lang}){ const steps=lang==='ar'?['تسجيل','تحليل','تنفيذ','اختبار','إطلاق','دعم']:['Intake','Analysis','Build','Test','Go Live','Support']; return <div className="panelPro"><div className="panelHeader"><h3>{lang==='ar'?'سير العمل':'Workflow'}</h3><Workflow size={18}/></div><div className="workflowSteps">{steps.map((s,i)=><div key={s} className={i<3?'active':''}><span>{i+1}</span><p>{s}</p></div>)}</div></div>; }
function ProjectTable({t,lang,projects,title}){ return <section className="panelPro tablePanel"><div className="panelHeader"><h3>{title || t.nav.portfolio}</h3><div className="viewTabs"><button className="active">Table</button><button>Detail</button></div></div><div className="tableWrap"><table><thead><tr><th>{t.project}</th><th>{t.owner}</th><th>{t.status}</th><th>{t.priority}</th><th>{t.progress}</th><th>{t.due}</th><th>{t.actions}</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><div className="projectTitle"><span>{p.id}</span><b>{n(p,lang)}</b></div></td><td>{p.owner}</td><td><Chip type={p.status}>{st(p.status,lang)}</Chip></td><td><Chip type={(p.priority||'Medium').toLowerCase()}>{pr(p.priority,lang)}</Chip></td><td><Progress value={p.progress}/></td><td>{p.due}</td><td><div className="rowActions"><Eye size={16}/><Edit3 size={16}/>{p.link&&<a href={p.link} target="_blank" rel="noreferrer"><LinkIcon size={16}/></a>}<MoreHorizontal size={16}/></div></td></tr>)}</tbody></table></div></section>; }
function Dashboard({t,lang,projects,setPage}){ const total=projects.length, tasks=projects.reduce((a,p)=>a+(Number(p.tasks)||0),0), risks=projects.reduce((a,p)=>a+(Number(p.risks)||0),0), avg=total?Math.round(projects.reduce((a,p)=>a+(Number(p.progress)||0),0)/total):0, util=total?Math.round(projects.reduce((a,p)=>a+(Number(p.util)||0),0)/total):0; return <><section className="commandCenter"><div className="quickCommands"><Cmd icon={Plus} label={lang==='ar'?'مشروع جديد':'New project'} tone="primary"/><Cmd icon={LayoutList} label="Table" onClick={()=>setPage('portfolio')}/><Cmd icon={KanbanSquare} label="Board" onClick={()=>setPage('board')}/><Cmd icon={CalendarDays} label="Calendar"/><Cmd icon={Mail} label={lang==='ar'?'تقرير أسبوعي':'Weekly report'} onClick={()=>setPage('reports')}/></div></section><section className="statsGrid"><Stat icon={BriefcaseBusiness} title={t.nav.portfolio} value={total} sub="Portfolio" tone="blue"/><Stat icon={ClipboardCheck} title={t.nav.tasks} value={tasks} sub="Open tasks" tone="green"/><Stat icon={AlertTriangle} title={t.nav.risks} value={risks} sub="Attention" tone="red"/><Stat icon={Gauge} title={t.progress} value={`${avg}%`} sub="Average" tone="purple"/><Stat icon={Users} title={t.nav.teams} value={`${util}%`} sub="Utilization" tone="amber"/></section><section className="dashboardGridPro"><PortfolioHealth t={t} projects={projects}/><Alerts t={t} lang={lang} projects={projects}/><WorkflowPanel lang={lang}/></section><ProjectTable t={t} lang={lang} projects={projects.slice(0,6)}/></>; }
function Board({t,lang,projects}){ const cols=[['blocked',t.blocked],['delayed',t.delayed],['on',t.on],['done',t.done]]; return <section className="boardPage">{cols.map(([s,label])=>{const items=projects.filter(p=>p.status===s); return <div className={`boardColumn ${s}`} key={s}><div className="boardHead"><b>{label}</b><span>{items.length}</span></div>{items.map(p=><div className="taskCard" key={p.id}><div className="taskTop"><b>{n(p,lang)}</b><MoreHorizontal size={16}/></div><p>{p.owner}</p><Progress value={p.progress}/><div className="taskMeta"><Chip type={(p.priority||'Medium').toLowerCase()}>{pr(p.priority,lang)}</Chip><span>{p.due}</span></div></div>)}</div>})}</section>; }
function Tasks({t,lang,data,projects}){ const list=(data.tasks||[]).length ? data.tasks.map((x,i)=>({ id:x.id||x.ID||`T-${i+1}`, ar:x.title||x.Title||x.TaskName||`مهمة ${i+1}`, en:x.title||x.Title||x.TaskName||`Task ${i+1}`, owner:x.owner||x.AssignedTo||x.PMOAssignedTo||'Team', status:statusFromText(x.status||x.Status, x.progress||0), priority:x.priority||x.Priority||'Medium', progress:Number(x.progress||x.Progress||x.PMOTaskProgress||0)||50, due:x.due||x.DueDate||x.PMOTaskDueDate||'' })) : projects.flatMap(p=>Array.from({length:Math.min(4,p.tasks||1)},(_,i)=>({id:`${p.id}-T${i+1}`,ar:`مهمة ${i+1} - ${p.ar}`,en:`Task ${i+1} - ${p.en}`,owner:p.owner,status:i%3===0?'blocked':i%2===0?'delayed':'on',priority:i%3===0?'High':'Medium',progress:Math.max(15,p.progress-(i*10)),due:p.due}))); return <ProjectTable t={t} lang={lang} projects={list} title={t.nav.tasks}/>; }
function Risks({t,lang,data,projects}){ const list=(data.risks||[]).length ? data.risks.map((x,i)=>({ id:x.id||x.ID||`R-${i+1}`, ar:x.title||x.Title||x.RiskTitle||`مخاطرة ${i+1}`, en:x.title||x.Title||x.RiskTitle||`Risk ${i+1}`, owner:x.owner||x.Owner||x.PMORiskOwner||'Owner', status:statusFromText(x.status||x.Status||x.Severity,0), priority:x.priority||x.Severity||'High', progress:0, due:x.due||x.DueDate||'' })) : projects.filter(p=>p.risks>0).map(p=>({id:`R-${p.id}`,ar:`مخاطر في ${p.ar}`,en:`Risk in ${p.en}`,owner:p.owner,status:p.status==='blocked'?'blocked':'delayed',priority:p.status==='blocked'?'Critical':'High',progress:100-p.progress,due:p.due})); return <ProjectTable t={t} lang={lang} projects={list} title={t.nav.risks}/>; }
function Team({lang,data}){ const resources=(data.resources||[]).length ? data.resources : [{name:'Haitham Elmohamady',role:'PMO Lead',load:82,status:'Available'},{name:'Sara Al-Mutairi',role:'Project Manager',load:73,status:'Normal'},{name:'Mohammed Al-Harbi',role:'Delivery Lead',load:96,status:'Overloaded'}]; return <section className="teamGrid">{resources.map((m,i)=><div className="teamCard" key={m.name||i}><div className="avatar">{norm(m.name||m.Employee||'T').slice(0,1)}</div><h3>{m.name||m.Employee}</h3><p>{m.role||m.Role}</p><Progress value={Number(m.load||m.Utilization||m.PMOUtilization||70)}/><Chip type={(Number(m.load||m.Utilization||70)>90)?'blocked':'on'}>{m.status||m.Status||'Available'}</Chip></div>)}</section>; }
function Reports({t,lang,projects,data}){ const total=projects.length, avg=total?Math.round(projects.reduce((a,p)=>a+p.progress,0)/total):0, blocked=projects.filter(p=>p.status==='blocked').length, delayed=projects.filter(p=>p.status==='delayed').length; return <section className="reportGrid"><div className="panelPro reportHero"><h3>{t.executive}</h3><p>{lang==='ar'?'ملخص تلقائي للحالة والإنجاز والمخاطر والتوصيات من SharePoint.':'Auto summary for status, progress, risks and recommendations from SharePoint.'}</p><div className="reportNumbers"><span><b>{total}</b>Projects</span><span><b>{avg}%</b>Progress</span><span><b>{blocked+delayed}</b>Attention</span></div><Cmd icon={Download} label={t.export} tone="primary"/></div><PortfolioHealth t={t} projects={projects}/><Alerts t={t} lang={lang} projects={projects}/><ProjectTable t={t} lang={lang} projects={projects.slice(0,8)} title={t.weekly}/></section>; }
function Files({lang,projects,data}){ const files=(data.files||[]).length ? data.files : projects.map(p=>({title:n(p,lang),count:p.files,link:p.link})); return <section className="filesGrid">{files.map((f,i)=><div className="fileCard" key={i}><Folder size={26}/><b>{f.title||f.name}</b><p>{f.count||f.files||0} files</p><a href={f.link||'#'} target="_blank" rel="noreferrer"><LinkIcon size={14}/> OneDrive / Teams</a></div>)}</section>; }
function Databases({t,lang,data,activeSheet,setActiveSheet,sheetQuery,setSheetQuery}){ const current=data.sheets?.find(s=>s.name===activeSheet)||data.sheets?.[0]; const rows=current?current.rows.filter(r=>r.some(c=>norm(c).toLowerCase().includes(sheetQuery.toLowerCase()))).slice(0,160):[]; return <section className="panelPro databasePage"><div className="databaseHero"><div><h3>{lang==='ar'?'Databases وقوائم التحكم':'Databases & Control Lists'}</h3><p>{lang==='ar'?'بيانات SharePoint و Excel كقوائم احترافية.':'SharePoint and Excel data as professional databases.'}</p></div><div className="dbStats"><span><b>{data.sheets?.length||0}</b>Sheets</span><span><b>{current?.rows?.length||0}</b>Rows</span><span><b>{current?.headers?.length||0}</b>Fields</span><span><b>{rows.length}</b>Results</span></div></div><div className="databaseToolbar"><div className="field"><label>{lang==='ar'?'اختر القائمة':'Select database'}</label><select value={current?.name||''} onChange={e=>setActiveSheet(e.target.value)}>{data.sheets?.length?data.sheets.map(s=><option key={s.name} value={s.name}>{s.name} - {s.rows.length}</option>):<option>{lang==='ar'?'ارفع ملف أو نفذ Sync':'Upload or run Sync'}</option>}</select></div><div className="databaseSearch"><Search size={16}/><input value={sheetQuery} onChange={e=>setSheetQuery(e.target.value)} placeholder={t.search}/></div></div>{current?<div className="tableWrap databaseTable"><table><thead><tr>{current.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{current.headers.map((h,j)=><td key={j}>{r[j]||'—'}</td>)}</tr>)}</tbody></table></div>:<div className="emptyState"><Upload size={36}/><b>{lang==='ar'?'نفذ سكربت المزامنة أو ارفع Excel':'Run sync script or upload Excel'}</b></div>}</section>; }
function Automation({lang}){ const rules=lang==='ar'?['إذا تأخر المشروع أرسل تنبيه للمدير','إذا زادت المخاطر أنشئ تصعيد','كل خميس أرسل تقرير أسبوعي','إذا تعدت الموارد 90% اعرض تحذير']:['If project is delayed send owner alert','If risks increase create escalation','Every Thursday send weekly report','If utilization exceeds 90% show warning']; return <section className="automationList">{rules.map((r,i)=><div className="automationRule" key={r}><Workflow size={22}/><div><b>{r}</b><p>{lang==='ar'?'جاهزة للربط مع Power Automate':'Ready for Power Automate'}</p></div><Chip type={i<2?'delayed':'on'}>{i<2?'Alert':'Auto'}</Chip></div>)}</section>; }
function SettingsPage({t,lang}){ return <section className="panelPro functionsPage"><div className="databaseHero"><div><h3>{lang==='ar'?'مركز التحكم والإعدادات':'Controls & Settings'}</h3><p>{lang==='ar'?'أزرار تشغيل وإدارة جاهزة.':'Ready operation controls.'}</p></div></div><div className="functionsGrid"><Cmd icon={Plus} label={t.newItem} tone="primary"/><Cmd icon={ClipboardCheck} label={t.nav.tasks}/><Cmd icon={AlertTriangle} label={t.nav.risks} tone="danger"/><Cmd icon={FileText} label={t.weekly}/><Cmd icon={Download} label={t.export}/><Cmd icon={Share2} label={t.share}/></div></section>; }
function Placeholder({label,lang}){ return <section className="panelPro placeholder"><Sparkles size={34}/><h3>{label}</h3><p>{lang==='ar'?'صفحة جاهزة للتطوير والربط.':'Ready page for integration and expansion.'}</p></section>; }

function App(){ const [lang,setLang]=React.useState('ar'); const [page,setPage]=React.useState('dashboard'); const [data,setData]=React.useState(SAMPLE); const [activeSheet,setActiveSheet]=React.useState(''); const [sheetQuery,setSheetQuery]=React.useState(''); const [filters,setFilters]=React.useState({status:'all',owner:'all',progress:'all'}); const t=COPY[lang];
 React.useEffect(()=>{ fetch('/data/sharepoint-data.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(j=>{ if(j){ const d=normalizeSharePointData(j); setData(d); setActiveSheet(d.sheets?.[0]?.name||''); } }).catch(()=>{}); },[]);
 const owners=['all',...Array.from(new Set(data.projects.map(p=>p.owner)))]; const projects=data.projects.filter(p=>(filters.status==='all'||p.status===filters.status)&&(filters.owner==='all'||p.owner===filters.owner)&&(filters.progress==='all'||(filters.progress==='low'?p.progress<50:filters.progress==='mid'?p.progress>=50&&p.progress<=80:p.progress>80))); async function upload(e){ const file=e.target.files?.[0]; if(!file)return; const buffer=await file.arrayBuffer(); const workbook=XLSX.read(buffer,{type:'array',cellDates:true}); const parsed=parseWorkbook(workbook,file.name); setData(parsed); setActiveSheet(parsed.sheets[0]?.name||''); setPage('databases'); }
 return <div className={`appShell ${lang==='ar'?'rtl':'ltr'}`} dir={lang==='ar'?'rtl':'ltr'}><TopBar t={t} lang={lang} setLang={setLang} upload={upload} source={data.source}/><Sidebar t={t} page={page} setPage={setPage}/><main className="mainArea"><PageHero t={t} page={page} source={data.source}/>{page==='dashboard'&&<><FilterDock t={t} filters={filters} setFilters={setFilters} owners={owners}/><Dashboard t={t} lang={lang} projects={projects} setPage={setPage}/></>}{page==='portfolio'&&<ProjectTable t={t} lang={lang} projects={projects}/>} {page==='board'&&<Board t={t} lang={lang} projects={projects}/>} {page==='tasks'&&<Tasks t={t} lang={lang} data={data} projects={projects}/>} {page==='risks'&&<Risks t={t} lang={lang} data={data} projects={projects}/>} {page==='teams'&&<Team lang={lang} data={data}/>} {page==='reports'&&<Reports t={t} lang={lang} projects={projects} data={data}/>} {page==='files'&&<Files lang={lang} projects={projects} data={data}/>} {page==='databases'&&<Databases t={t} lang={lang} data={data} activeSheet={activeSheet} setActiveSheet={setActiveSheet} sheetQuery={sheetQuery} setSheetQuery={setSheetQuery}/>} {page==='automation'&&<Automation lang={lang}/>} {page==='settings'&&<SettingsPage t={t} lang={lang}/>} {!['dashboard','portfolio','board','tasks','risks','teams','reports','files','databases','automation','settings'].includes(page)&&<Placeholder label={t.nav[page]||page} lang={lang}/>}</main></div>; }

createRoot(document.getElementById('root')).render(<App />);
