import React from 'react';
import { createRoot } from 'react-dom/client';
import * as XLSX from 'xlsx';
import {
  AlertTriangle, BarChart3, Bell, BriefcaseBusiness, CalendarDays, ClipboardCheck,
  Database, Download, Edit3, Eye, FileText, Filter, Folder, Gauge, Home,
  KanbanSquare, Languages, Link as LinkIcon, MoreHorizontal, Plus, RefreshCcw,
  Search, Settings, Share2, ShieldCheck, Sparkles, Trash2, Upload, Users,
  Workflow, Save, ListChecks
} from 'lucide-react';
import './styles.css';
import './forms.css';

const LS_KEY = 'pmo-control-hub-records-v6';
const TYPES = ['projects', 'tasks', 'risks', 'reports', 'resources', 'schedules', 'files'];
const EMPTY = Object.fromEntries(TYPES.map((type) => [type, []]));

const COPY = {
  en: {
    app: 'Project Control Hub',
    sub: 'Professional PMO workspace for portfolio, delivery, schedules, resources and reporting',
    search: 'Search workspace...', upload: 'Upload Excel', save: 'Save Record', export: 'Export', share: 'Share', refresh: 'Refresh', new: 'New Record', filters: 'Filters', backend: 'Backend', connected: 'Connected', local: 'Local fallback',
    nav: { dashboard: 'Dashboard', portfolio: 'Portfolio', board: 'Board', tasks: 'Tasks', risks: 'Risks', schedule: 'Schedule', teams: 'Resources', reports: 'Reports', files: 'Files', databases: 'Databases', forms: 'All Lists' },
    status: { all: 'All', on: 'On Track', delayed: 'Delayed', blocked: 'At Risk', done: 'Completed', open: 'Open' },
    labels: { project: 'Project', owner: 'Owner', status: 'Status', priority: 'Priority', progress: 'Progress', due: 'Due', actions: 'Actions', health: 'Health Score', budget: 'Budget Utilization', active: 'Active Projects', total: 'Total Projects', risks: 'Open Risks', tasks: 'Attention Tasks', team: 'Team Utilization', milestones: 'Milestones' }
  },
  ar: {
    app: 'مركز التحكم بالمشاريع',
    sub: 'مساحة PMO احترافية لإدارة المحفظة والتنفيذ والجداول والموارد والتقارير',
    search: 'بحث في النظام...', upload: 'رفع Excel', save: 'حفظ السجل', export: 'تصدير', share: 'مشاركة', refresh: 'تحديث', new: 'سجل جديد', filters: 'الفلاتر', backend: 'قاعدة البيانات', connected: 'متصل', local: 'محلي',
    nav: { dashboard: 'الرئيسية', portfolio: 'المحفظة', board: 'البورد', tasks: 'المهام', risks: 'المخاطر', schedule: 'الجدول الزمني', teams: 'الموارد', reports: 'التقارير', files: 'الملفات', databases: 'القواعد', forms: 'كل القوائم' },
    status: { all: 'الكل', on: 'على المسار', delayed: 'متأخر', blocked: 'خطر', done: 'مكتمل', open: 'مفتوح' },
    labels: { project: 'المشروع', owner: 'المالك', status: 'الحالة', priority: 'الأولوية', progress: 'الإنجاز', due: 'الموعد', actions: 'إجراءات', health: 'مؤشر الصحة', budget: 'استخدام الميزانية', active: 'المشاريع النشطة', total: 'إجمالي المشاريع', risks: 'المخاطر المفتوحة', tasks: 'مهام تحتاج متابعة', team: 'استخدام الفريق', milestones: 'المعالم' }
  }
};

const MODULES = {
  projects: {
    page: 'portfolio', icon: BriefcaseBusiness, tone: 'blue', title: 'Project Portfolio', ar: 'محفظة المشاريع', desc: 'Official register for all projects, contracts, owners, progress and SharePoint links.',
    fields: [['en', 'Project Name', 'text'], ['ar', 'Arabic Name', 'text'], ['owner', 'Project Manager', 'text'], ['department', 'Business Line / Department', 'text'], ['client', 'Client', 'text'], ['region', 'Region', 'text'], ['status', 'Status', 'select:on,delayed,blocked,done'], ['priority', 'Priority', 'select:Low,Medium,High,Critical'], ['progress', 'Progress %', 'number'], ['start', 'Start Date', 'date'], ['due', 'End Date', 'date'], ['budget', 'Budget %', 'number'], ['util', 'Team Utilization %', 'number'], ['link', 'Project SharePoint / OneDrive Link', 'url'], ['notes', 'Notes', 'textarea']]
  },
  tasks: {
    page: 'tasks', icon: ClipboardCheck, tone: 'green', title: 'Team Task Board', ar: 'مهام الفريق', desc: 'Assign, monitor and close team tasks by project, owner, priority and due date.',
    fields: [['project', 'Project', 'project'], ['title', 'Task Title', 'text'], ['owner', 'Assigned To', 'text'], ['status', 'Status', 'select:open,on,delayed,blocked,done'], ['priority', 'Priority', 'select:Low,Medium,High,Critical'], ['progress', 'Progress %', 'number'], ['due', 'Due Date', 'date'], ['notes', 'Notes', 'textarea']]
  },
  risks: {
    page: 'risks', icon: AlertTriangle, tone: 'red', title: 'Risk & Issue Register', ar: 'سجل المخاطر والمشكلات', desc: 'Track project risks, issues, severity, probability and mitigation actions.',
    fields: [['project', 'Project', 'project'], ['title', 'Risk / Issue Title', 'text'], ['owner', 'Risk Owner', 'text'], ['severity', 'Severity', 'select:Low,Medium,High,Critical'], ['status', 'Status', 'select:open,on,delayed,blocked,done'], ['impact', 'Impact', 'select:Low,Medium,High,Critical'], ['probability', 'Probability', 'select:Low,Medium,High,Critical'], ['due', 'Target Date', 'date'], ['mitigation', 'Mitigation Plan', 'textarea']]
  },
  schedules: {
    page: 'schedule', icon: CalendarDays, tone: 'purple', title: 'Schedule & Milestones', ar: 'الجداول الزمنية والمعالم', desc: 'Control plans, milestones, phases, baseline dates and progress updates.',
    fields: [['project', 'Project', 'project'], ['milestone', 'Milestone / Phase', 'text'], ['owner', 'Owner', 'text'], ['start', 'Start Date', 'date'], ['due', 'End Date', 'date'], ['status', 'Status', 'select:on,delayed,blocked,done'], ['progress', 'Progress %', 'number'], ['notes', 'Notes', 'textarea']]
  },
  resources: {
    page: 'teams', icon: Users, tone: 'cyan', title: 'Resource Allocation', ar: 'توزيع الموارد', desc: 'Manage resource capacity, planned hours, actual hours and utilization by project.',
    fields: [['name', 'Employee', 'text'], ['role', 'Role', 'text'], ['department', 'Department', 'text'], ['project', 'Project', 'project'], ['capacity', 'Capacity Hours', 'number'], ['planned', 'Planned Hours', 'number'], ['actual', 'Actual Hours', 'number'], ['util', 'Utilization %', 'number'], ['status', 'Status', 'select:Available,Normal,Overloaded,Unavailable']]
  },
  reports: {
    page: 'reports', icon: FileText, tone: 'amber', title: 'Status Reports', ar: 'تقارير الحالة', desc: 'Create weekly and executive reports with achievements, challenges and next steps.',
    fields: [['project', 'Project', 'project'], ['date', 'Report Date', 'date'], ['health', 'Overall Health', 'select:on,delayed,blocked,done'], ['achievements', 'Achievements', 'textarea'], ['challenges', 'Challenges', 'textarea'], ['nextSteps', 'Next Steps', 'textarea'], ['support', 'Support Needed', 'textarea']]
  },
  files: {
    page: 'files', icon: Folder, tone: 'slate', title: 'Files Register', ar: 'سجل الملفات', desc: 'Register project documents, folders, OneDrive, Teams and SharePoint links.',
    fields: [['project', 'Project', 'project'], ['title', 'File / Folder Title', 'text'], ['type', 'Document Type', 'select:Schedule,Report,Contract,MOM,Deliverable,Template,Other'], ['owner', 'Owner', 'text'], ['date', 'Updated Date', 'date'], ['link', 'Document Link', 'url'], ['notes', 'Notes', 'textarea']]
  }
};

const SAMPLE = { source: { type: 'sample', updatedAt: new Date().toISOString() }, projects: [
  { id: 'P-001', en: 'EPM-IDT Phase 3', ar: 'التحول الرقمي للحوكمة', owner: 'Mohamed Ahmed', department: 'Le Source', client: 'EPM', region: 'EPM', status: 'on', priority: 'Medium', progress: 70, start: '2024-01-01', due: '2026-12-30', budget: 73, util: 70, tasks: 8, risks: 1, files: 12 },
  { id: 'P-002', en: 'EPM-Cleaning', ar: 'الإشراف على النظافة', owner: 'Mohamed Idris', department: 'Le Source', client: 'EPM', region: 'EPM', status: 'delayed', priority: 'High', progress: 35, start: '2025-11-03', due: '2028-11-02', budget: 82, util: 79, tasks: 16, risks: 4, files: 22 },
  { id: 'P-003', en: 'EPM-940 Phase 5', ar: 'إدارة بلاغات 940', owner: 'Mohamed Al Khatem', department: 'Le Source', client: 'EPM', region: 'EPM', status: 'on', priority: 'Medium', progress: 92, start: '2025-12-10', due: '2028-12-09', budget: 66, util: 82, tasks: 7, risks: 1, files: 16 }
], tasks: [], risks: [], resources: [], reports: [], schedules: [], files: [], sheets: [] };

const norm = (v) => v == null ? '' : String(v).trim();
const num = (v, d = 0) => Number.isFinite(Number(v)) ? Number(v) : d;
const titleOf = (r, lang) => lang === 'ar' ? (r.ar || r.title || r.name || r.en || r.project || '—') : (r.en || r.title || r.name || r.ar || r.project || '—');
const loadLocal = () => { try { return JSON.parse(localStorage.getItem(LS_KEY)) || EMPTY; } catch { return EMPTY; } };
const saveLocal = (v) => localStorage.setItem(LS_KEY, JSON.stringify(v));
const uid = (type) => `${type.slice(0, 1).toUpperCase()}-${Date.now()}`;
function downloadJson(name, data) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
async function apiList(type) { const r = await fetch(`/api/records${type ? `?type=${type}` : ''}`, { cache: 'no-store' }); const j = await r.json(); if (!r.ok) throw new Error(j.error || 'API failed'); return j.rows || []; }
async function apiCreate(type, record) { const r = await fetch('/api/records', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, record }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error || 'API failed'); return j.row; }
async function apiDelete(id, type) { const r = await fetch('/api/records', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, type }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error || 'API failed'); return j; }

function Chip({ type, children }) { return <span className={`chip ${type}`}>{children}</span>; }
function Progress({ value }) { const v = Math.max(0, Math.min(100, num(value))); return <div className="progress"><span><i style={{ width: `${v}%` }} /></span><b>{v}%</b></div>; }
function Cmd({ icon: Icon, label, tone = '', onClick }) { return <button className={`commandButton ${tone}`} onClick={onClick}><Icon size={16} /><span>{label}</span></button>; }
function Stat({ icon: Icon, title, value, sub, tone }) { return <div className="statCard"><div className={`statIcon ${tone}`}><Icon size={22} /></div><div><p>{title}</p><strong>{value}</strong><span>{sub}</span></div></div>; }

function sheetToRows(ws) { const matrix = XLSX.utils.sheet_to_json(ws, { header: 1, raw: false, defval: '' }); const headerIndex = Math.max(0, matrix.findIndex((row) => row.filter((cell) => norm(cell)).length >= 3)); const headers = (matrix[headerIndex] || []).map((x, i) => norm(x) || `Column ${i + 1}`); const rows = matrix.slice(headerIndex + 1).map((row) => headers.map((_, i) => norm(row[i]))).filter((row) => row.some(Boolean)); return { headers, rows }; }
function parseWorkbook(workbook, fileName) { const sheets = workbook.SheetNames.map((name) => ({ name, ...sheetToRows(workbook.Sheets[name]) })); const sourceRows = sheets.find((s) => /project|erp|solution/i.test(s.name))?.rows || sheets.flatMap((s) => s.rows.slice(0, 2)); const projects = sourceRows.slice(0, 60).map((r, i) => ({ id: r[0] || `P-${i + 1}`, department: r[1] || '', client: r[2] || '', region: r[2] || '', ar: r[3] || r[1] || '', en: r[4] || r[1] || r[0] || `Project ${i + 1}`, owner: r[7] || r[2] || 'Project Manager', status: 'on', priority: 'Medium', progress: 60, start: r[5] || '', due: r[6] || '', budget: 70, util: 70, tasks: 0, risks: 0, files: 0 })); return { ...SAMPLE, source: { type: 'excel', workbook: fileName, updatedAt: new Date().toISOString() }, sheets, projects: projects.length ? projects : SAMPLE.projects }; }

function TopBar({ t, lang, setLang, upload, backendState }) { return <header className="topBar"><div className="brand"><div className="brandLogo"><Workflow size={22} /></div><div><b>{t.app}</b><span>{t.sub}</span></div></div><div className="globalSearch"><Search size={18} /><input placeholder={t.search} /></div><div className="dataSource"><Database size={15} /><span>{t.backend}: {backendState === 'connected' ? t.connected : t.local}</span></div><div className="topActions"><label className="uploadBtn"><Upload size={16} />{t.upload}<input type="file" accept=".xlsx,.xls,.xlsm" onChange={upload} /></label><button onClick={() => setLang(lang === 'en' ? 'ar' : 'en')}><Languages size={16} />{lang === 'en' ? 'AR' : 'EN'}</button><button><Bell size={16} /></button><button><Settings size={16} /></button></div></header>; }
function Sidebar({ t, page, setPage }) { const nav = [['dashboard', Home], ['portfolio', BriefcaseBusiness], ['board', KanbanSquare], ['tasks', ClipboardCheck], ['risks', AlertTriangle], ['schedule', CalendarDays], ['teams', Users], ['reports', BarChart3], ['files', Folder], ['databases', Database], ['forms', ListChecks]]; return <aside className="sidebar"><div className="workspaceCard"><Sparkles size={18} /><div><b>PMO Workspace</b><span>Projects • Teams • Delivery</span></div></div><nav>{nav.map(([k, Icon]) => <button key={k} className={page === k ? 'active' : ''} onClick={() => setPage(k)}><Icon size={18} /><span>{t.nav[k]}</span></button>)}</nav><div className="sideNote"><ShieldCheck size={18} /><p>Each PMO list now has its own dedicated form page and data table.</p></div></aside>; }
function Hero({ t, page, setPage, refresh, exportAll }) { return <section className="pageHero"><div><div className="breadcrumb"><Home size={14} /><span>PMO</span><span>/</span><span>{t.nav[page]}</span></div><h1>{t.nav[page] === 'All Lists' || t.nav[page] === 'كل القوائم' ? 'PMO List Center' : t.app}</h1><p>{t.sub}</p></div><div className="heroActions"><Cmd icon={Plus} label={t.new} tone="primary" onClick={() => setPage(page === 'dashboard' ? 'portfolio' : page)} /><Cmd icon={RefreshCcw} label={t.refresh} onClick={refresh} /><Cmd icon={Download} label={t.export} onClick={exportAll} /><Cmd icon={Share2} label={t.share} /></div></section>; }
function Filters({ t, filters, setFilters, projects }) { const unique = (k) => [...new Set(projects.map((p) => p[k]).filter(Boolean))]; return <section className="filterDock"><div><Filter size={16} /><b>{t.filters}</b></div><select value={filters.owner} onChange={(e) => setFilters({ ...filters, owner: e.target.value })}><option value="all">Project Manager: {t.status.all}</option>{unique('owner').map((x) => <option key={x}>{x}</option>)}</select><select value={filters.department} onChange={(e) => setFilters({ ...filters, department: e.target.value })}><option value="all">Department: {t.status.all}</option>{unique('department').map((x) => <option key={x}>{x}</option>)}</select><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="all">Project Status: {t.status.all}</option><option value="on">{t.status.on}</option><option value="delayed">{t.status.delayed}</option><option value="blocked">{t.status.blocked}</option><option value="done">{t.status.done}</option></select><select value={filters.region} onChange={(e) => setFilters({ ...filters, region: e.target.value })}><option value="all">Region: {t.status.all}</option>{unique('region').map((x) => <option key={x}>{x}</option>)}</select></section>; }

function Dashboard({ t, projects, tasks, risks, resources }) { const total = projects.length; const active = projects.filter((p) => p.status !== 'done').length; const avg = total ? Math.round(projects.reduce((a, p) => a + num(p.progress), 0) / total) : 0; const util = resources.length ? Math.round(resources.reduce((a, r) => a + num(r.util), 0) / resources.length) : 68; const openRisks = risks.length || projects.reduce((a, p) => a + num(p.risks), 0); const delayed = tasks.filter((x) => x.status === 'delayed' || x.status === 'blocked').length || projects.filter((p) => ['delayed', 'blocked'].includes(p.status)).length * 3; return <><section className="statsGrid pm-kpis"><Stat icon={BriefcaseBusiness} title={t.labels.total} value={total} sub="Portfolio scope" tone="blue" /><Stat icon={Folder} title={t.labels.active} value={active} sub="In delivery" tone="purple" /><Stat icon={Gauge} title={t.labels.budget} value={`${Math.round(projects.reduce((a, p) => a + num(p.budget), 0) / (total || 1))}%`} sub="Average" tone="green" /><Stat icon={BarChart3} title={t.labels.health} value={`${avg}/100`} sub="Portfolio score" tone="amber" /><Stat icon={AlertTriangle} title={t.labels.risks} value={openRisks} sub="Risk items" tone="red" /><Stat icon={ClipboardCheck} title={t.labels.tasks} value={delayed} sub="Need attention" tone="red" /><Stat icon={Users} title={t.labels.team} value={`${util}%`} sub="Capacity" tone="purple" /><Stat icon={CalendarDays} title={t.labels.milestones} value={projects.filter((p) => num(p.progress) > 80).length} sub="Tracked" tone="blue" /></section><section className="pm-grid"><Gantt projects={projects} /><Health projects={projects} /><Bars title="Resource Allocation by Department" rows={groupAvg(projects, 'department', 'util')} /><Heat /><Milestones projects={projects} /><Trend /><Bars title="Project Status by Department" rows={groupAvg(projects, 'department', 'progress')} /><Workload resources={resources} /></section></>; }
const groupAvg = (rows, k, m) => Object.entries(rows.reduce((g, r) => { const x = r[k] || 'Other'; (g[x] ||= []).push(num(r[m], 60)); return g; }, {})).map(([name, arr]) => ({ name, value: Math.round(arr.reduce((a, b) => a + b, 0) / arr.length) })).slice(0, 6);
function Gantt({ projects }) { return <div className="panelPro pm-card pm-gantt"><div className="panelHeader"><h3>Project Gantt Chart</h3><MoreHorizontal size={16} /></div><div className="ganttHead"><span>Project Name</span><span>% Complete</span><span>Jan</span><span>Mar</span><span>May</span><span>Jul</span><span>Sep</span><span>Dec</span></div>{projects.slice(0, 7).map((p, i) => <div className="ganttRow" key={p.id || p.en}><b>{p.en || p.title}</b><em>{p.progress || 0}%</em><div className="ganttTrack"><i className={p.status} style={{ marginLeft: `${(i * 9) % 35}%`, width: `${Math.max(18, Math.min(70, num(p.progress)))}%` }} /></div></div>)}</div>; }
function Health({ projects }) { const total = projects.length || 1; const on = projects.filter((p) => p.status === 'on').length; const delay = projects.filter((p) => p.status === 'delayed').length; const block = projects.filter((p) => p.status === 'blocked').length; const done = projects.filter((p) => p.status === 'done').length; return <div className="panelPro pm-card"><div className="panelHeader"><h3>Projects by Progress</h3></div><div className="pulseBody"><div className="donutPro" style={{ background: `conic-gradient(#2563eb 0 ${on / total * 100}%,#f59e0b ${on / total * 100}% ${(on + delay) / total * 100}%,#ef4444 ${(on + delay) / total * 100}% ${(on + delay + block) / total * 100}%,#16a34a ${(on + delay + block) / total * 100}% 100%)` }}><span>{total}<small>Total</small></span></div><div className="legendPro"><p><i className="green" />On Track<b>{on}</b></p><p><i className="amber" />Delayed<b>{delay}</b></p><p><i className="red" />At Risk<b>{block}</b></p><p><i className="gray" />Completed<b>{done}</b></p></div></div></div>; }
function Bars({ title, rows }) { return <div className="panelPro pm-card"><div className="panelHeader"><h3>{title}</h3></div><div className="miniBars">{rows.map((r) => <p key={r.name}><span>{r.name}</span><i><b style={{ width: `${r.value}%` }} /></i><em>{r.value}%</em></p>)}</div></div>; }
function Heat() { return <div className="panelPro pm-card"><div className="panelHeader"><h3>Risk Heat Map</h3></div><div className="heatMap">{Array.from({ length: 25 }).map((_, i) => <i key={i} className={`h${Math.min(4, Math.max(0, Math.floor(i / 5) + i % 5 - 2))}`} />)}</div></div>; }
function Trend() { return <div className="panelPro pm-card"><div className="panelHeader"><h3>Task Completion Trend</h3></div><div className="trendLine"><b>73%</b></div></div>; }
function Milestones({ projects }) { return <div className="panelPro pm-card"><div className="panelHeader"><h3>Milestone Tracking</h3></div><div className="milestones"><div className="donutPro"><span>{projects.filter((p) => p.progress > 80).length}</span></div><p><b>Completed</b><span>{projects.filter((p) => p.progress > 80).length}</span></p><p><b>In Progress</b><span>{projects.filter((p) => p.progress <= 80 && p.progress > 40).length}</span></p><p><b>Delayed</b><span>{projects.filter((p) => p.status !== 'on').length}</span></p></div></div>; }
function Workload({ resources }) { const rows = resources.length ? resources : [{ name: 'Mohamed Idris', role: 'PM', util: 70 }, { name: 'Mohamed Ahmed', role: 'PM', util: 72 }, { name: 'Rami Mamoon', role: 'Lead', util: 78 }, { name: 'Khaled Sultan', role: 'Lead', util: 82 }]; return <div className="panelPro pm-card"><div className="panelHeader"><h3>Team Workload</h3></div><div className="workload">{rows.slice(0, 6).map((r) => <p key={r.name}><b>{r.name}</b><span>{r.role || r.department}</span><Progress value={r.util || r.load} /></p>)}</div></div>; }

function Table({ t, lang, rows, title, onDelete, type }) { return <section className="panelPro tablePanel"><div className="panelHeader"><h3>{title}</h3><div className="viewTabs"><button className="active">Table</button><button>Detail</button></div></div><div className="tableWrap"><table><thead><tr><th>{t.labels.project}</th><th>{t.labels.owner}</th><th>{t.labels.status}</th><th>{t.labels.priority}</th><th>{t.labels.progress}</th><th>{t.labels.due}</th><th>{t.labels.actions}</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r._backendId || r.id || i}><td><div className="projectTitle"><span>{r.id || r._backendId || `#${i + 1}`}</span><b>{titleOf(r, lang)}</b></div></td><td>{r.owner || r.name || '—'}</td><td><Chip type={r.status || r.health}>{t.status[r.status || r.health] || r.status || '—'}</Chip></td><td><Chip type={(r.priority || r.severity || 'Medium').toLowerCase()}>{r.priority || r.severity || 'Medium'}</Chip></td><td><Progress value={r.progress || r.util} /></td><td>{r.due || r.date || '—'}</td><td><div className="rowActions"><Eye size={16} /><Edit3 size={16} />{r.link && <a href={r.link} target="_blank" rel="noreferrer"><LinkIcon size={16} /></a>}{r._backendId && <button className="iconButton" onClick={() => onDelete(r._backendId, type)}><Trash2 size={16} /></button>}<MoreHorizontal size={16} /></div></td></tr>)}</tbody></table></div></section>; }
function Board({ t, lang, projects }) { const cols = [['blocked', t.status.blocked], ['delayed', t.status.delayed], ['on', t.status.on], ['done', t.status.done]]; return <section className="boardPage">{cols.map(([s, label]) => <div className={`boardColumn ${s}`} key={s}><div className="boardHead"><b>{label}</b><span>{projects.filter((p) => p.status === s).length}</span></div>{projects.filter((p) => p.status === s).map((p) => <div className="taskCard" key={p.id || p._backendId}><div className="taskTop"><b>{titleOf(p, lang)}</b><MoreHorizontal size={16} /></div><p>{p.owner}</p><Progress value={p.progress} /><div className="taskMeta"><Chip type={(p.priority || 'Medium').toLowerCase()}>{p.priority}</Chip><span>{p.due}</span></div></div>)}</div>)}</section>; }

function ModuleWorkspace({ type, t, lang, onSave, onDelete, projects, records }) { const cfg = MODULES[type]; const Icon = cfg.icon; const [form, setForm] = React.useState({}); const [saving, setSaving] = React.useState(false); const rows = records[type] || []; async function save() { setSaving(true); await onSave(type, { ...form, id: form.id || uid(type), createdAt: new Date().toISOString() }); setForm({}); setSaving(false); } function field(key, label, def) { const [kind, opts] = def.split(':'); if (kind === 'project') return <select value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })}><option value="">Select project</option>{projects.map((p) => <option key={p.id || p.en} value={p.en || p.name}>{p.en || p.name}</option>)}</select>; if (kind === 'textarea') return <textarea value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />; if (kind === 'select') return <select value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })}><option value="">Select</option>{opts.split(',').map((o) => <option key={o} value={o}>{o}</option>)}</select>; return <input type={kind} value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />; } return <section className={`modulePage ${cfg.tone}`}><div className="moduleHero"><div className="moduleIcon"><Icon size={24} /></div><div><h2>{lang === 'ar' ? cfg.ar : cfg.title}</h2><p>{cfg.desc}</p></div><div className="moduleActions"><Cmd icon={Save} label={saving ? 'Saving...' : t.save} tone="primary" onClick={save} /><Cmd icon={Download} label="Export" onClick={() => downloadJson(`${type}.json`, rows)} /></div></div><div className="moduleLayout"><div className="panelPro moduleForm"><div className="panelHeader"><h3>New {cfg.title}</h3><Chip type="on">Dedicated form</Chip></div><div className="moduleFields">{cfg.fields.map(([key, label, def]) => <label key={key} className={def === 'textarea' ? 'wide' : ''}><span>{label}</span>{field(key, label, def)}</label>)}</div></div><div className="panelPro moduleList"><div className="panelHeader"><h3>{cfg.title} Records</h3><span>{rows.length}</span></div><div className="moduleMiniRows">{rows.slice(0, 10).length ? rows.slice(0, 10).map((r, i) => <div key={r._backendId || r.id || i}><b>{titleOf(r, lang)}</b><span>{r.owner || r.status || r.project || '—'}</span><em>{r.due || r.date || r.createdAt || ''}</em>{r._backendId && <button onClick={() => onDelete(r._backendId, type)}><Trash2 size={14} /></button>}</div>) : <p>No records yet. Add the first record using the form.</p>}</div></div></div><Table t={t} lang={lang} rows={rows.map((x) => ({ ...x, en: x.en || x.title || x.milestone || x.name, ar: x.ar || x.title || x.milestone || x.name, priority: x.priority || x.severity || 'Medium' }))} title={`${cfg.title} Table`} onDelete={onDelete} type={type} /></section>; }
function FormsCenter({ t, lang, setPage, records }) { return <section className="listHub"><div className="hubHeader"><h2>PMO List Center</h2><p>Choose the module you want to update. Each list has a separate page, dedicated form and table.</p></div><div className="hubGrid">{Object.entries(MODULES).map(([type, cfg]) => { const Icon = cfg.icon; return <button key={type} className={`hubCard ${cfg.tone}`} onClick={() => setPage(cfg.page)}><Icon size={24} /><b>{lang === 'ar' ? cfg.ar : cfg.title}</b><span>{cfg.desc}</span><em>{(records[type] || []).length} records</em></button>; })}</div></section>; }
function TeamCards({ resources }) { return <section className="teamGrid">{resources.map((r, i) => <div className="teamCard" key={r._backendId || r.id || i}><div className="avatar">{norm(r.name || 'T').slice(0, 1)}</div><h3>{r.name}</h3><p>{r.role || r.department}</p><Progress value={r.util || r.load} /><Chip type={num(r.util || r.load) > 90 ? 'blocked' : num(r.util || r.load) > 75 ? 'delayed' : 'on'}>{r.status || 'Available'}</Chip></div>)}</section>; }
function Databases({ t, data, team, backend, local, activeSheet, setActiveSheet, query, setQuery }) { const make = (name, arr) => ({ name, headers: Object.keys(arr[0] || {}), rows: arr.map((x) => Object.keys(arr[0] || {}).map((h) => x[h])) }); const sheets = [...(data.sheets || []), ...(team.sheets || []), ...TYPES.map((k) => make(`Backend ${k}`, backend[k] || [])).filter((s) => s.rows.length), ...TYPES.map((k) => make(`Local ${k}`, local[k] || [])).filter((s) => s.rows.length)]; const current = sheets.find((s) => s.name === activeSheet) || sheets[0]; const rows = current ? current.rows.filter((r) => r.some((c) => norm(c).toLowerCase().includes(query.toLowerCase()))).slice(0, 200) : []; return <section className="panelPro databasePage"><div className="databaseHero"><div><h3>Databases & Control Lists</h3><p>Backend, SharePoint, Excel and local records in one clean review area.</p></div><div className="dbStats"><span><b>{sheets.length}</b>Tables</span><span><b>{current?.rows?.length || 0}</b>Rows</span><span><b>{current?.headers?.length || 0}</b>Fields</span><span><b>{rows.length}</b>Results</span></div></div><div className="databaseToolbar"><div className="field"><label>Select database</label><select value={current?.name || ''} onChange={(e) => setActiveSheet(e.target.value)}>{sheets.map((s) => <option key={s.name} value={s.name}>{s.name} - {s.rows.length}</option>)}</select></div><div className="databaseSearch"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t.search} /></div></div>{current ? <div className="tableWrap databaseTable"><table><thead><tr>{current.headers.map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{current.headers.map((h, j) => <td key={j}>{String(r[j] ?? '—')}</td>)}</tr>)}</tbody></table></div> : <div className="emptyState"><Database size={36} /><b>No data yet</b></div>}</section>; }

function App() { const [lang, setLang] = React.useState('en'); const [page, setPage] = React.useState('dashboard'); const [data, setData] = React.useState(SAMPLE); const [team, setTeam] = React.useState({ resources: [], sheets: [] }); const [local, setLocal] = React.useState(loadLocal); const [backend, setBackend] = React.useState(EMPTY); const [backendState, setBackendState] = React.useState('fallback'); const [activeSheet, setActiveSheet] = React.useState(''); const [query, setQuery] = React.useState(''); const [filters, setFilters] = React.useState({ owner: 'all', department: 'all', status: 'all', region: 'all' }); const t = COPY[lang];
  async function refresh() { try { const rows = await apiList(); const next = { ...EMPTY }; rows.forEach((r) => { if (next[r.type]) next[r.type].push({ ...r.record, _backendId: r.id, _createdAt: r.created_at }); }); setBackend(next); setBackendState('connected'); } catch { setBackendState('fallback'); } }
  React.useEffect(() => { fetch('/data/sharepoint-data.json', { cache: 'no-store' }).then((r) => r.ok ? r.json() : null).then((j) => { if (j) { setData({ ...SAMPLE, ...j }); setActiveSheet(j.sheets?.[0]?.name || ''); } }).catch(() => {}); fetch('/data/team-data.json', { cache: 'no-store' }).then((r) => r.ok ? r.json() : null).then((j) => { if (j) setTeam(j); }).catch(() => {}); refresh(); }, []);
  async function onSave(type, record) { try { const row = await apiCreate(type, record); setBackend((p) => ({ ...p, [type]: [{ ...row.record, _backendId: row.id }, ...(p[type] || [])] })); setBackendState('connected'); } catch { const next = { ...local, [type]: [record, ...(local[type] || [])] }; setLocal(next); saveLocal(next); setBackendState('fallback'); } }
  async function onDelete(id, type) { try { await apiDelete(id, type); setBackend((p) => ({ ...p, [type]: p[type].filter((x) => x._backendId !== id) })); } catch (e) { alert(e.message); } }
  async function upload(e) { const file = e.target.files?.[0]; if (!file) return; const buffer = await file.arrayBuffer(); const workbook = XLSX.read(buffer, { type: 'array', cellDates: true }); const parsed = parseWorkbook(workbook, file.name); setData(parsed); setActiveSheet(parsed.sheets[0]?.name || ''); setPage('databases'); }
  const projects = [...(data.projects || []), ...backend.projects, ...local.projects]; const tasks = [...backend.tasks, ...local.tasks]; const risks = [...backend.risks, ...local.risks]; const resources = [...(team.resources || []), ...backend.resources, ...local.resources]; const reports = [...backend.reports, ...local.reports]; const files = [...backend.files, ...local.files]; const schedules = [...backend.schedules, ...local.schedules]; const records = { projects, tasks, risks, resources, reports, schedules, files }; const filtered = projects.filter((p) => (filters.owner === 'all' || p.owner === filters.owner) && (filters.department === 'all' || p.department === filters.department) && (filters.status === 'all' || p.status === filters.status) && (filters.region === 'all' || p.region === filters.region)); const exportAll = () => downloadJson('pmo-full-export.json', { data, team, backend, local, exportedAt: new Date().toISOString() });
  return <div className={`appShell ${lang === 'ar' ? 'rtl' : 'ltr'}`} dir={lang === 'ar' ? 'rtl' : 'ltr'}><TopBar t={t} lang={lang} setLang={setLang} upload={upload} backendState={backendState} /><Sidebar t={t} page={page} setPage={setPage} /><main className="mainArea"><Hero t={t} page={page} setPage={setPage} refresh={refresh} exportAll={exportAll} />{page === 'dashboard' && <><Filters t={t} filters={filters} setFilters={setFilters} projects={projects} /><Dashboard t={t} projects={filtered} tasks={tasks} risks={risks} resources={resources} /></>}{page === 'portfolio' && <ModuleWorkspace type="projects" t={t} lang={lang} onSave={onSave} onDelete={onDelete} projects={projects} records={records} />}{page === 'tasks' && <ModuleWorkspace type="tasks" t={t} lang={lang} onSave={onSave} onDelete={onDelete} projects={projects} records={records} />}{page === 'risks' && <ModuleWorkspace type="risks" t={t} lang={lang} onSave={onSave} onDelete={onDelete} projects={projects} records={records} />}{page === 'schedule' && <ModuleWorkspace type="schedules" t={t} lang={lang} onSave={onSave} onDelete={onDelete} projects={projects} records={records} />}{page === 'teams' && <><ModuleWorkspace type="resources" t={t} lang={lang} onSave={onSave} onDelete={onDelete} projects={projects} records={records} /><TeamCards resources={resources} /></>}{page === 'reports' && <ModuleWorkspace type="reports" t={t} lang={lang} onSave={onSave} onDelete={onDelete} projects={projects} records={records} />}{page === 'files' && <ModuleWorkspace type="files" t={t} lang={lang} onSave={onSave} onDelete={onDelete} projects={projects} records={records} />}{page === 'board' && <Board t={t} lang={lang} projects={filtered} />}{page === 'databases' && <Databases t={t} data={data} team={team} backend={backend} local={local} activeSheet={activeSheet} setActiveSheet={setActiveSheet} query={query} setQuery={setQuery} />}{page === 'forms' && <FormsCenter t={t} lang={lang} setPage={setPage} records={records} />}</main></div>;
}

createRoot(document.getElementById('root')).render(<App />);
